name: 'ESLint Check Action'
description: 'Runs ESLint Checks and bails if there is a failure'
branding:
    icon: 'check-circle'
    color: 'blue'
inputs:
    eslintConfig:
        required: false
        description: 'Path to your ESLint Config. Defaults to ".eslintrc.js"'
    eslintFolder:
        required: false
        description: 'Where ESLint should look for the files. Defaults to "."'
    authToken:
        required: false
        description: 'GitHub AuthToken'
runs:
    using: 'node12'
    main: 'dist/eslint.action.js'
